[package]
name = "crator"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-only"
readme = "README.md"
description = "A lightweight Cargo package registry"
homepage = "https://github.com/dnaka91/crator"
repository = "https://github.com/dnaka91/crator"
keywords = ["crates"]

[dependencies]
anyhow = "1.0.31"
askama = { version = "0.9.0", default-features = false }
diesel = { version = "1.4.5", features = ["r2d2", "sqlite"] }
diesel_migrations = "1.4.0"
git2 = "0.13.6"
libsqlite3-sys = { version = "0.18.0", features = ["bundled"] }
log = { version = "0.4.8", features = ["release_max_level_info"] }
maplit = "1.0.2"
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "async" }
semver = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.55"
tokio = { version = "0.2.21", features = ["blocking"] }
url = { version = "2.1.1", features = ["serde"] }

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "async"
default-features = false
features = ["helmet", "json"]

[profile.release]
lto = true
panic = "abort"
