[package]
name = "crator"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-only"
readme = "README.md"
description = "A lightweight Cargo package registry"
homepage = "https://github.com/dnaka91/crator"
repository = "https://github.com/dnaka91/crator"
keywords = ["crates"]

[dependencies]
anyhow = "1.0.37"
askama = { version = "0.10.5", default-features = false }
async-trait = "0.1.42"
git2 = "0.13.15"
hex = "0.4.2"
log = { version = "0.4.11", features = ["release_max_level_info"] }
r2d2 = "0.8.9"
r2d2_sqlite = "0.17.0"
refinery = { version = "0.5.0", features = ["rusqlite"] }
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master" }
rusqlite = "0.24.2"
semver = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
sha2 = "0.9.2"
tokio = { version = "0.2.22", features = ["blocking", "macros"] }
tracing = { version = "0.1.22", features = ["release_max_level_info"] }
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
url = { version = "2.2.0", features = ["serde"] }

[dependencies.derive_more]
version = "0.99.11"
default-features = false
features = ["display"]

[dependencies.config]
version = "0.10.1"
default-features = false
features = ["toml"]

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
branch = "master"
default-features = false
features = ["helmet", "json"]

[profile.release]
lto = true
panic = "abort"

[dev-dependencies]
maplit = "1.0.2"
tempfile = "3.1.0"
