[package]
name = "asgard"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
rust-version = "1.56"
license = "AGPL-3.0-only"
readme = "README.md"
description = "A lightweight Cargo package registry"
homepage = "https://github.com/dnaka91/asgard"
repository = "https://github.com/dnaka91/asgard"
keywords = ["crates"]

[dependencies]
anyhow = "1.0.44"
askama = { version = "0.10.5", default-features = false, features = ["with-warp"] }
askama_warp = "0.11.0"
async-trait = "0.1.51"
derive_more = { version = "0.99.16", default-features = false, features = ["display"] }
git2 = { version = "0.13.23", features = ["vendored-libgit2", "vendored-openssl"] }
hex = "0.4.3"
hyper = "0.14.13"
log = "0.4.14"
parking_lot = "0.11.2"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
refinery = { version = "0.7.0", features = ["rusqlite"] }
rusqlite = { version = "0.25.3", features = ["bundled"] }
semver = { version = "1.0.4", features = ["serde"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sha2 = "0.9.8"
thiserror = "1.0.30"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
tokio-util = "0.6.8"
toml = "0.5.8"
tracing = "0.1.29"
tracing-subscriber = "0.2.25"
url = { version = "2.2.2", features = ["serde"] }
warp = { version = "0.3.1", default-features = false }

[profile.release]
lto = true

[dev-dependencies]
maplit = "1.0.2"
tempfile = "3.2.0"
