[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "asgard", version = "*" },
]

[bans]
skip = [
    { name = "parking_lot", version = "=0.11.2" },
    { name = "parking_lot_core", version = "=0.8.5" },
    { name = "tokio-util", version = "=0.6.10" },
    { name = "wasi", version = "=0.10.2" },
]
