[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "asgard", version = "*" },
]

[bans]
skip = [
    { name = "hashbrown", version = "=0.9.1" },
    { name = "nom", version = "=5.1.2" },
]

[sources]
allow-git = ["https://github.com/rust-db/refinery.git"]
