[advisories]
ignore = ["RUSTSEC-2021-0139"]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "asgard" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "hashbrown", version = "=0.11.2" },
    { name = "tokio-util", version = "=0.6.10" },
]
